package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"time"
)

const fileHeader = `// Code generated by internal/sarsync. DO NOT EDIT.
//
// Source: https://servicereference.us-east-1.amazonaws.com/
// Generated: %s
// Services: %d
// Patterns: %d
//
// Regenerate with:
//
//	go run ./internal/sarsync

package arn

import "regexp"

`

// generate emits the Go source for arn/services_generated.go from rules.
func generate(rules []rule) ([]byte, error) {
	var buf bytes.Buffer

	totalPatterns := 0
	for _, r := range rules {
		totalPatterns += len(r.patterns)
	}

	fmt.Fprintf(&buf, fileHeader, time.Now().UTC().Format(time.RFC3339), len(rules), totalPatterns)

	buf.WriteString("//nolint:gochecknoglobals // generated read-only lookup table\n")
	buf.WriteString("var serviceRules = map[string]serviceRule{\n")

	for _, r := range rules {
		fmt.Fprintf(&buf, "\t%q: {\n", r.service)
		buf.WriteString("\t\tarnFormats: []*regexp.Regexp{\n")

		for _, p := range r.patterns {
			fmt.Fprintf(&buf, "\t\t\tregexp.MustCompile(%s),\n", quoteRawOrInterpreted(p))
		}

		buf.WriteString("\t\t},\n")
		buf.WriteString("\t},\n")
	}

	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Return the unformatted source for debugging if go/format fails.
		return buf.Bytes(), fmt.Errorf("go/format: %w", err)
	}

	return formatted, nil
}

// quoteRawOrInterpreted prefers a backtick-quoted raw string for readability,
// falling back to a double-quoted string when the pattern contains a backtick.
func quoteRawOrInterpreted(p string) string {
	if !strings.ContainsRune(p, '`') {
		return "`" + p + "`"
	}

	return fmt.Sprintf("%q", p)
}
